### ISSUE TITLE
Coefficient Length and Polynomial Order Discrepencies

### ISSUE THREAD

**Issue by agerlach** [JuliaApproximation/RecurrenceRelationships.jl#15]
When I used `forwardrecurrence` I was surprised that it didn't evaluate `Pn(x)` given that the length of the arguments provides enough information to compute it. In other words, the last element of the arguments is ignored. 

```julia
n = 10
A = fill(2, n); B = zeros(n); C = ones(n)
res1 = forwardrecurrence(A, B, C, 1/2)

A[end] = -typemax(Int)
B[end] = -typemax(Int)
C[end] = -typemax(Int)
forwardrecurrence(A, B, C, 1/2) == res1 #true
```

From an interface perspective, I expected to evaluate Pn  vs the first n including P0. For my particular application I only know A, B, C up to n and need to compute Pn, so I need to artificially pad my vectors to get the correct output. So, its not really a bug, but the output seems inconsistent given the input.

**Comment by dlfivefifty** [comment]
Thanks for pointing this out. I tend to use the ∞ version (I.e. `forwardrecurrence(10, Fill(2,∞), Zeros(∞), Ones(∞), 1/2)` so haven't put much thought into the finite version.

Would you be willing to make a PR to fix this?

**Comment by agerlach** [comment]
Yeah.

**Comment by agerlach** [comment]
@dlfivefifty Can I get a release for this? Thanks.
